# Generated by Django 3.2 on 2021-05-16 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StravaApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(blank=True, max_length=120, null=True)),
                ('club', models.CharField(blank=True, max_length=120, null=True)),
                ('website', models.CharField(blank=True, max_length=120, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('callback_domain', models.CharField(max_length=120)),
                ('client_id', models.CharField(max_length=5)),
                ('client_secret', models.CharField(max_length=40)),
                ('refresh_token', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('app', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='connections.stravaapp')),
                ('code', models.CharField(blank=True, max_length=40, null=True)),
                ('access_token', models.CharField(blank=True, max_length=40, null=True)),
                ('refresh_token', models.CharField(blank=True, max_length=40, null=True)),
                ('scope', models.CharField(blank=True, max_length=120, null=True)),
                ('token_type', models.CharField(blank=True, max_length=120, null=True)),
                ('expires_at', models.IntegerField(blank=True, null=True)),
                ('expires_in', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
