# Generated by Django 3.2.3 on 2021-07-01 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0004_auto_20210505_0152'),
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='app',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='socialaccount.socialapp'),
        ),
        migrations.DeleteModel(
            name='StravaApp',
        ),
    ]
