# Generated by Django 3.2.3 on 2021-07-13 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0003_auto_20210701_0459'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
