# Generated by Django 3.2.3 on 2021-07-21 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stravaprofile',
            name='avatar_url',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
    ]
