# Generated by Django 3.2.3 on 2021-07-23 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0004_stravaprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stravaprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='strava_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
