# Generated by Django 3.2 on 2021-05-16 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=127)),
                ('start_lat', models.FloatField(blank=True, null=True)),
                ('start_lng', models.FloatField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('start_date_local', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SegmentEffort',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('elapsed_time', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('start_date_local', models.DateTimeField(blank=True, null=True)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('pr_rank', models.IntegerField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.activity')),
                ('segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.segment')),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polyline', models.TextField(blank=True, null=True)),
                ('Segment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='activities.segment')),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='activities.activity')),
            ],
        ),
    ]
