# Generated by Django 3.2.10 on 2022-09-21 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('start_date_local', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['-start_date_local'],
            },
        ),
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('icon', models.CharField(blank=True, max_length=127, null=True)),
                ('color', models.CharField(blank=True, max_length=31, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polyline', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('kom', models.CharField(blank=True, max_length=20, null=True)),
                ('qom', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SegmentEffort',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('elapsed_time', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('start_date_local', models.DateTimeField(blank=True, null=True)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('pr_rank', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['start_date_local'],
            },
        ),
        migrations.CreateModel(
            name='StaredSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.segment')),
            ],
        ),
    ]
