# Generated by Django 3.2 on 2021-05-16 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_auto_20210516_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='activity',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.activity'),
        ),
        migrations.AlterField(
            model_name='map',
            name='segment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.segment'),
        ),
    ]
