# Generated by Django 3.2 on 2021-05-17 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_auto_20210516_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='staring',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
