# Generated by Django 3.2 on 2021-05-17 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_segment_staring'),
    ]

    operations = [
        migrations.RenameField(
            model_name='map',
            old_name='activity',
            new_name='activity_id',
        ),
        migrations.RenameField(
            model_name='map',
            old_name='segment',
            new_name='segment_id',
        ),
        migrations.RenameField(
            model_name='segmenteffort',
            old_name='activity',
            new_name='activity_id',
        ),
        migrations.RenameField(
            model_name='segmenteffort',
            old_name='segment',
            new_name='segment_id',
        ),
    ]
