# Generated by Django 3.2 on 2021-05-17 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_auto_20210517_0519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='map',
            old_name='activity_id',
            new_name='activity',
        ),
        migrations.RenameField(
            model_name='map',
            old_name='segment_id',
            new_name='segment',
        ),
        migrations.RenameField(
            model_name='segmenteffort',
            old_name='activity_id',
            new_name='activity',
        ),
        migrations.RenameField(
            model_name='segmenteffort',
            old_name='segment_id',
            new_name='segment',
        ),
    ]
