# Generated by Django 3.2 on 2021-05-18 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_auto_20210517_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='start_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='segment',
            name='start_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
