# Generated by Django 3.2 on 2021-05-21 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_auto_20210518_0009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='segment',
            old_name='staring',
            new_name='starred',
        ),
    ]
