# Generated by Django 3.2 on 2021-05-21 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_rename_staring_segment_starred'),
    ]

    operations = [
        migrations.RenameField(
            model_name='segment',
            old_name='starred',
            new_name='staring',
        ),
    ]
