# Generated by Django 3.2.3 on 2021-05-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0009_rename_starred_segment_staring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='segment',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='segmenteffort',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
