# Generated by Django 3.2.3 on 2021-07-29 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0016_alter_staredsegment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='icon',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
    ]
