# Generated by Django 3.2.3 on 2021-08-17 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0018_auto_20210817_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='start_lat',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_lng',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
