# Generated by Django 3.2.3 on 2021-08-17 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0020_auto_20210817_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
