# Generated by Django 3.2.10 on 2022-04-11 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0025_auto_20220410_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='type',
        ),
    ]
