# Generated by Django 3.2.10 on 2022-04-11 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0026_auto_20220411_0117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='activity_type',
            new_name='type',
        ),
    ]
