# Generated by Django 3.2.10 on 2022-07-27 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0028_rename_type_activitytype_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-start_date_local'], 'verbose_name_plural': 'Activities'},
        ),
    ]
