# Generated by Django 3.2.10 on 2022-08-08 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0029_alter_activity_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.activitytype'),
        ),
    ]
