# Generated by Django 3.2.3 on 2021-08-13 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetActivitiesTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('frequency', models.IntegerField(choices=[('Daily', 1), ('Weekly', 7), ('Monthly', 30)], default='Weekly', max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('periodic_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_beat.periodictask')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='get_activities_task', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
