# Generated by Django 3.2.10 on 2022-09-21 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportActivitiesTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('from_date', models.DateTimeField(blank=True, null=True)),
                ('to_date', models.DateTimeField(blank=True, null=True)),
                ('frequency', models.IntegerField(choices=[(7, 'Weekly'), (30, 'Monthly')], default=30)),
                ('n_intervals', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SyncActivitiesTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('from_date', models.DateTimeField(blank=True, null=True)),
                ('to_date', models.DateTimeField(blank=True, null=True)),
                ('frequency', models.IntegerField(choices=[(1, 'Daily'), (7, 'Weekly'), (30, 'Monthly')], default=7)),
                ('active', models.BooleanField(default=False)),
                ('crontab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_beat.crontabschedule')),
                ('periodic_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_beat.periodictask')),
            ],
        ),
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.CharField(blank=True, max_length=255, null=True)),
                ('import_task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='getactivities.importactivitiestask')),
                ('sync_task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='getactivities.syncactivitiestask')),
            ],
        ),
    ]
