# Generated by Django 3.2.3 on 2021-08-13 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getactivities', '0002_alter_getactivitiestask_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getactivitiestask',
            name='frequency',
            field=models.IntegerField(choices=[(1, 'Daily'), (7, 'Weekly'), (30, 'Monthly')], default=7),
        ),
    ]
