# Generated by Django 3.2.3 on 2021-08-19 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getactivities', '0004_auto_20210817_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getactivitiestask',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
