# Generated by Django 3.2.3 on 2021-08-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getactivities', '0005_alter_getactivitiestask_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getactivitiestask',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='getactivitiestask',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
