# Generated by Django 3.2.3 on 2021-08-21 05:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('getactivities', '0006_auto_20210820_1910'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GetActivitiesTask',
            new_name='FetchActivitiesTask',
        ),
    ]
