# Generated by Django 3.2.3 on 2021-08-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getactivities', '0007_rename_getactivitiestask_fetchactivitiestask'),
    ]

    operations = [
        migrations.AddField(
            model_name='fetchactivitiestask',
            name='to_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fetchactivitiestask',
            name='frequency',
            field=models.IntegerField(choices=[(7, 'Weekly'), (30, 'Monthly')], default=30),
        ),
    ]
