# Generated by Django 3.2.3 on 2021-08-25 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('getactivities', '0009_fetchactivitiestask_n_intervals'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetActivitiesTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('frequency', models.IntegerField(choices=[(1, 'Daily'), (7, 'Weekly'), (30, 'Monthly')], default=7)),
                ('active', models.BooleanField(default=False)),
                ('periodic_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_beat.periodictask')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='get_activities_task', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImportActivitiesTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('to_date', models.DateTimeField(blank=True, null=True)),
                ('frequency', models.IntegerField(choices=[(7, 'Weekly'), (30, 'Monthly')], default=30)),
                ('n_intervals', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('periodic_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_beat.periodictask')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='import_activities_task', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='FetchActivitiesTask',
        ),
    ]
