# Generated by Django 3.2.3 on 2021-08-27 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getactivities', '0010_auto_20210825_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='getactivitiestask',
            name='day',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
