# Generated by Django 3.2.3 on 2021-09-19 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('getactivities', '0012_auto_20210827_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncactivitiestask',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sync_activities_task', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Task_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.CharField(blank=True, max_length=255, null=True)),
                ('import_task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='getactivities.importactivitiestask')),
                ('sync_task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='getactivities.syncactivitiestask')),
            ],
        ),
    ]
