# Generated by Django 3.2.10 on 2022-03-30 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
        ('getactivities', '0014_auto_20220329_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncactivitiestask',
            name='crontab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_beat.crontabschedule'),
        ),
    ]
