# Generated by Django 3.2.10 on 2022-04-01 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getactivities', '0015_syncactivitiestask_crontab'),
    ]

    operations = [
        migrations.AddField(
            model_name='importactivitiestask',
            name='from_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
