# Generated by Django 3.2.10 on 2022-04-01 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getactivities', '0016_importactivitiestask_from_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='importactivitiestask',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
