# Generated by Django 3.2.10 on 2022-04-10 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getactivities', '0017_importactivitiestask_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task_log',
            new_name='TaskLog',
        ),
    ]
